import { Application } from "@hotwired/stimulus";
import DashboardPageController from "./controllers/dashboard_page_controller";
import ContactsPageController from "./controllers/contacts_page_controller";
import MarketInsightsController from "./controllers/market_insights_controller";
import GroupsPageController from "./controllers/groups_page_controller";
import DailyBriefingController from "./controllers/daily_briefing_controller";
import DailyBriefingBannerController from "./controllers/daily_briefing_banner_controller";
import BriefingChatController from "./controllers/briefing_chat_controller";
import TransactionLiveController from "./controllers/transaction_live_controller";
import DocumentReviewWorkspaceController from "./controllers/document_review_workspace_controller";
import AmendmentReviewController from "./controllers/amendment_review_controller";
import OfferCompareController from "./controllers/offer_compare_controller";
import DocumentUploadHubController from "./controllers/document_upload_hub_controller";
import OfferPackageReviewController from "./controllers/offer_package_review_controller";
import ListingInfoCompareController from "./controllers/listing_info_compare_controller";
import MarketingCampaignMonitorController from "./controllers/marketing_campaign_monitor_controller";
import MarketingCampaignWizardController from "./controllers/marketing_campaign_wizard_controller";
import MarketingTemplateLibraryController from "./controllers/marketing_template_library_controller";
import MarketingTemplateStudioController from "./controllers/marketing_template_studio_controller";
import "./analytics";
import "./styles/app.css";

const application = Application.start();

application.register("dashboard-page", DashboardPageController);
application.register("contacts-page", ContactsPageController);
application.register("market-insights", MarketInsightsController);
application.register("groups-page", GroupsPageController);
application.register("daily-briefing", DailyBriefingController);
application.register("daily-briefing-banner", DailyBriefingBannerController);
application.register("briefing-chat", BriefingChatController);
application.register("transaction-live", TransactionLiveController);
application.register("document-review-workspace", DocumentReviewWorkspaceController);
application.register("amendment-review", AmendmentReviewController);
application.register("offer-compare", OfferCompareController);
application.register("document-upload-hub", DocumentUploadHubController);
application.register("offer-package-review", OfferPackageReviewController);
application.register("listing-info-compare", ListingInfoCompareController);
application.register("marketing-campaign-monitor", MarketingCampaignMonitorController);
application.register("marketing-campaign-wizard", MarketingCampaignWizardController);
application.register("marketing-template-library", MarketingTemplateLibraryController);
application.register("marketing-template-studio", MarketingTemplateStudioController);

window.Stimulus = application;
