"""Change docuseal_template_id and docuseal_submission_id to String

Revision ID: 57f483948875
Revises: add_company_update_engagement
Create Date: 2026-01-03 15:47:35.004131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '57f483948875'
down_revision = 'add_company_update_engagement'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_todo_list', schema=None) as batch_op:
        batch_op.alter_column('todo_content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)

    with op.batch_alter_table('transaction_documents', schema=None) as batch_op:
        batch_op.alter_column('docuseal_template_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('docuseal_submission_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_documents', schema=None) as batch_op:
        batch_op.alter_column('docuseal_submission_id',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('docuseal_template_id',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('daily_todo_list', schema=None) as batch_op:
        batch_op.alter_column('todo_content',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)

    # ### end Alembic commands ###
